name: foodbalance4
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.3.0
  cloud_firestore: ^5.2.1
  firebase_auth: ^5.1.4
  openai_dart: ^0.1.0
  http: ^1.2.2
  dash_chat_2: ^0.0.21
  image_picker: ^1.1.2
  flutter_gemini: ^2.0.5
  camera: ^0.11.0+2
  firebase_ml_model_downloader: ^0.3.1+1
  tflite_flutter: ^0.11.0
  image: ^4.2.0
  percent_indicator: ^4.2.3
  fl_chart: ^0.69.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/tflite/model_unquant.tflite
    - assets/tflite/labels.txt
    - assets/images/1.jpg
    - assets/images/2.png